[tool.pyright]
include = ["src", "examples", "tests"]
exclude = ["**/__pycache__", "**/node_modules", "**/venv", "**/.venv"]
pythonVersion = "3.8"
typeCheckingMode = "basic"

[tool.pytest.ini_options]
pythonpath = ["."]


